name: Java CI

on:
  push:
    tags:
      - '*-Beta'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 16
        graalvm-version: 21.1.0
        native-image: true

    - name: Show status
      run: |
        echo event=${{ github.event_name }}
        echo action=${{ github.event.action }}
        echo ref=${{ github.ref }}
        echo merge=${{ github.event.pull_request.merged }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/TriggerReactor-*.jar
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        prerelease: true
